spring:
  application:
    name: forohub
  datasource:
    url: jdbc:mysql://localhost/forohub
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    secret: ${JWT_SECRET}
