CREATE TABLE IF NOT EXISTS topicos(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(255) NOT NULL,
    mensaje VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status ENUM("ACTIVO", "RESUELTO") NOT NULL,
    id_autor BIGINT,
    curso VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_autor) REFERENCES usuarios(id) ON DELETE SET NULL
);